name: metadata-extract

on:
  schedule:
    - cron: '0 0 * * *' # every night at midnight UTC

  workflow_dispatch:
  
jobs:
  run-cron-extract:
    runs-on: ubuntu-latest


    steps:
      - name: checkout-code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: setup-uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0

      - name: setup-python
        run: uv python install

      - name: install-project
        run: uv sync --locked
      
      - name: collect-metadata
        env: 
          PORTAL_PAL_API_KEY: ${{ secrets.PORTAL_PAL_API_KEY }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        run: uv run ./apps/metadata-extract/src/metadata-extract/main.py
      
